// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sypbxjvsrixualmwumyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cGJ4anZzcml4dWFsbXd1bXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjczNTYsImV4cCI6MjA2NTIwMzM1Nn0.1tpZ88Cuoii1oFzI7gvdgDa_pTmnGBhxRMaaLUi-G2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);